version: "3.7"

services:
  backend:
    container_name: app_backend
    restart: always
    build: .
    environment:
      - APP_ENV=development
      - APP_PORT=9000
    volumes:
      - ./src:/var/www/app/src
      - ./test:/var/www/app/test
    working_dir: /var/www/app
    ports:
      - "9001:9000"
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
  mysql: 
    container_name: app_mysql
    restart: always
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=app_docker
    ports:
    - "3308:3306"
    volumes:
    - app_mysql_data:/var/lib/mysql
  redis: # Example Service
    container_name: app_redis
    restart: always
    image: redis:6.0-alpine
    expose:
      - "6379"
    volumes:
      - app_redis_data:/data

volumes:
  app_mysql_data:
  app_redis_data:

networks:
  default:
    external:
      name: app-docker