version: "3.7"

services:
  mysql: 
    container_name: app_mysql
    restart: always
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=app_docker
    ports:
    - "3308:3306"
    volumes:
    - app_mysql_data:/var/lib/mysql
  redis:
    container_name: app_redis
    restart: always
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - app_redis_data:/data

volumes:
  app_mysql_data:
  app_redis_data:
